name: ChromaBlock
version: '1.1-SNAPSHOT'
main: fr.chiroyuki.chromaBlock.ChromaBlock
api-version: '1.21'

commands:
  chroma:
    description: Commande principale de ChromaBlock
    usage: /<command> <save|delete|list|give>
